Feat/33 combine notifs
neatchee/mastodon pull request #38
Opened 2023-01-29 09:31 UTC by deanveloper

Summary of changes:

 * name_list
   * New component, represents a localized list of names.
 * status
   * Changed `account` prop (the prop indicating a "related" account, such as who favorited a post inside of a notification) to optionally be a list of accounts
 * status_header
   * The "status header" is the profile picture.
   * Changed `friend` prop to `friends` to prepare for being able to show multiple profile pictures for the multiple accounts that favorited the post.
   * (While the propname changed, I haven't implemented the feature yet)
 * status_prepend
   * The "status prepend" is a component which prepends a status, usually used for notifications, says things like "x favorited your post"
 * status_container
   * swapped priority of `account` vs `props.account`... might need to check for regressions here but I haven't found any so far.
 * notification_container
   * just switched to new property name accountIds
 * notifications/index.js
   * bulk of the actual logic, groups notifications together and turns the `account` prop into an account list
 * selectors/index.js
   * expect a list of accounts instead of a single account

TODO - add a setting, probably in the notifications options, which allows people to toggle this feature on/off

2023-01-30 00:05 UTC, deanveloper commented
earlier there were issues regarding some other components which expected `account` to be a single account instead of an array, for now I've made it so that `notification.account` is just a single acount when possible, the only way for it to be an array is for favorite/reblog notifications

2023-01-30 01:41 UTC, deanveloper commented
Should be ready to go! We can add more things to group by later as well. For now I just have boosts and favorites.

![image](https://user-images.githubusercontent.com/3196327/215370267-73e2e39b-7a59-4469-8d17-77b7d8695864.png)

2023-02-04 02:19 UTC, neatchee requested changes

2023-02-04 02:19 UTC, neatchee commented on app/javascript/flavours/glitch/components/status.js
> +          { name: new Intl.ListFormat(intl.locale, { type: 'conjunction' }).format(accounts.map(acct => acct.get('acct'))) },
Is this unsorted?
We should make sure we're always the most recent accounts to have boosted/favorited the status

2023-02-04 02:19 UTC, neatchee commented on app/javascript/flavours/glitch/features/notifications/index.js
> -    const { intl, notifications, isLoading, isUnread, columnId, multiColumn, hasMore, numPending, showFilterBar, lastReadId, canMarkAsRead, needsNotificationPermission } = this.props;
Is there a reason this was removed? IDE cleaned it up I'm guessing?

2023-02-04 02:26 UTC, deanveloper commented on app/javascript/flavours/glitch/components/status.js
> +          { name: new Intl.ListFormat(intl.locale, { type: 'conjunction' }).format(accounts.map(acct => acct.get('acct'))) },
It should be sorted by recent-first since that's the order the grouping function puts them in, I'll check again when I add reactions

2023-02-04 02:29 UTC, deanveloper commented on app/javascript/flavours/glitch/features/notifications/index.js
> -    const { intl, notifications, isLoading, isUnread, columnId, multiColumn, hasMore, numPending, showFilterBar, lastReadId, canMarkAsRead, needsNotificationPermission } = this.props;
Yeah, I instead decided to calculate the `notifications` variable based on user settings instead of coming directly from props (see line 268).

Might clean the up the code down there since it looks a bit more confusing than I'd like.

2023-02-04 02:30 UTC, neatchee approved these changes

2023-02-04 02:30 UTC, merged